---
title: "PA1_template"
author: "Sebastián Castillo"
date: "7 de octubre de 2016"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(dplyr)
library(ggplot2)
library(data.table)
library(lattice)

# Loading and preprocessing the data 
setwd("C:/Users/sebastian/Google Drive/Formación Personal/DataScience/Especialización en John Hopkins")
activity <- read.csv('activity.csv', header = TRUE, sep = ",", colClasses=c("numeric", "character", "numeric"))
```

```{r}
complete_days_only <- activity[complete.cases(activity), ]
```

## What is mean total number of steps taken per day?

```{r}
step_summary  <-  complete_days_only %>% 
                  group_by(date) %>% 
                  summarise(daily_step_count = sum(steps))
hist(step_summary$daily_step_count, 
    main = "Histogram of total steps per day",
    xlab = "Range of step totals",
    ylab = "Number of totals in range",
    col = heat.colors(5),
    las = 1,
    ylim = c(0, 30))

```

## What is the average daily activity pattern?

```{r}
x  <- complete_days_only %>% 
      group_by(interval) %>% 
      summarise(avg_interval = mean(steps))


plot(x$interval, 
     x$avg_interval, 
     type = "l", 
     las = 1, 
     col = "chocolate4", 
     main = "Average Steps within Intervals",
     col.main = "blue",
     font.main = 4,
     xlab = "Daily Intervals",
     ylab = "Step Averages"
     )
x[which.max(x$avg_interval), ]

```

## Imputing missing values

```{r}
nrow(activity)
nrow(complete_days_only)

set.seed(1234)
z  <- floor(runif(nrow(activity), 
                  min = min(activity$steps, na.rm = T), 
                  max = max(activity$steps, na.rm = T)/10))

w  <- which(is.na(activity$steps))

activity$steps[w]  <- z[w]

complete_data  <- activity %>% 
                  group_by(date) %>% 
                  summarise(daily_step_count = sum(steps))
hist(complete_data$daily_step_count, 
    breaks = 10,
    main = "Histogram of total steps per day",
    xlab = "Range of step totals",
    ylab = "Number of totals in range",
    col = heat.colors(12),
    las = 1,
    ylim = c(0, 25))
```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
activity$date <- as.POSIXct(activity$date)

activity$dayType  <- ifelse(weekdays(activity$date) %in% c("Saturday", "Sunday"), "weekend", "weekday")

activity$dayType  <- as.factor(activity$dayType)

q  <- activity %>% group_by(dayType, interval) %>% summarise(daily_step_count = sum(steps))

with(q, xyplot(daily_step_count ~ interval | dayType, type = "l",      
      main = "Total Steps within Intervals",
      xlab = "Daily Intervals",
      ylab = "Total Steps"))

```


